#! /bin/bash
HELP_STRING="\
Usage: ./start_ui [options]\n

start_ui will start up a ui for this auto cleaning trolley\n
\n
Options:\r\n
\t--help\t\t           show this help message and exit\n\n
\tstart \t\t        start ui program and video recorder\n\n
\tstop \t\t      stop all ui program\n\n
\tinstall\t\t    install this ui program to this computer,\n
                 \t\t   \t  if success,this computer will reboot\n\n
\tuninstall\t uninstall this ui program to this computer,\n
                    \t\t \t if success,this computer will reboot\n\n
\ttest 100\t begin to start a startup test, 100 is startup times,\n\n
\tdeltest\t stop startup test, delete start_ini and move tmp.csv to 2019xxxx_undone.csv \n\n
\n
\n
\tSee www.baidu.com\n
"
fun_start()
{
    RET=$(pgrep -f ui_main)
    if [ "" == "$RET" ]
    then
        echo "start uio"
        cd /home/utry/release/bin/ui
        ./ui_main&
    fi
}
fun_stop()
{
    sudo kill -9 $(ps -ef |grep ui_main|grep -v grep|awk '{print $2}')
    sudo kill -9 $(ps -ef |grep ros|grep -v grep|awk '{print $2}')
}
fun_install()
{
    EXE_PATH=`pwd`
    sudo cp /home/utry/release/utry_shell/start_ui /usr/bin/
    cd ~/release/utry_shell/
    ./install_program.sh
    cd $EXE_PATH
}
fun_uninstall()
{
    EXE_PATH=`pwd`
    cd ~/release/utry_shell/
    ./uninstall_program.sh
    cd $EXE_PATH
}
fun_showhelp()
{
    echo -e $HELP_STRING
}
# shellcheck disable=SC2120
fun_showerror()
{
    echo "$1 command is not support!"
    fun_showhelp
}
if [ "" == "$1" ]; then
    echo "begin to start ui"
    fun_start
elif [ "start" == "$1" ];then
    echo "begin to start ui"
    fun_start
elif [ "stop" == "$1" ];then
    echo "begin to stop ui"
    fun_stop
elif [ "install" == "$1" ];then
    echo "begin to install ui"
    fun_install
elif [ "uninstall" == "$1" ];then
    echo "begin to uninstall ui"
    fun_uninstall
elif [ "--help" == "$1" ];then
    fun_showhelp
elif [ "test" == "$1" ];then
    # shellcheck disable=SC1073
    # shellcheck disable=SC1073
    if [ "" != "$2" ]; then
      echo "begin to test"
      sudo echo "$2" > /home/utry/release/utry_shell/start_ini
      echo "clear log file"
      rm /home/utry/release/log/utry_*
      echo "wait for reboot"
      sleep 2
      sudo reboot
    else
      echo 'please input cnt'
    fi
elif [ "deltest" == "$1" ];then

  sudo kill -9 $(ps -ef |grep start_test|grep -v grep|awk '{print $2}')
  EXE_PATH=`pwd`
  cd /home/utry/release/utry_shell

  rm ./start_ini
  currentfile=$(date +%Y%m%d%H%M%S)
  echo "save undone file to ${currentfile}_undone.csv"
  if ! test -d ./record
  then
    mkdir record
  fi
  mv ./tmp.csv ./record/${currentfile}_undone.csv
  zip -r record_${currentfile}_undone.zip ./record/*
  rm ./record/ -rf
  cd $EXE_PATH
else
    fun_showerror
fi


